### ISSUE TITLE
Set a `twaManifest.generatorApp` to `nuxt-twa`

### ISSUE THREAD

**Issue by andreban** [tuarrep/nuxt-twa#1]
This information is useful when developer have issue with their application and we can use that get details on how it's been generated. This can be added my including the code segment below [here](https://github.com/tuarrep/nuxt-twa/blob/master/src/tasks/generateTWAManifest.ts#L16):

```ts
twaManifest.generatorApp = 'nuxt-twa';
```

**Comment by tuarrep** [comment]
Thanks for pointing this out!

I'll make the change ASAP unless you open a PR before

**Comment by andreban** [comment]
I'm not familiar with the stack, but hoping this is enough
